name: Node.js CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: 'master'
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - run: npm install
    - run: node index.js
