name: Node.js CI

on:
  push:
    branches: 
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'dev'
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - run: npm install
    - run: npm run build --if-present
      env:
        CI: true
