name: Node.js CI

on: [push]

jobs:
  build:
    name: 'test deploy'
    if: github.ref == 'red/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - run: npm install
    - run: node index.js
